[package]
name = "http_io"
version = "0.1.0"
authors = ["Remi Bernotavicius <remi@abort.cc>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = """
A library with limited dependencies containing an HTTP client and server.
"""

[dependencies]
