[package]
name = "http_io"
version = "0.2.3"
authors = ["Remi Bernotavicius <remi@abort.cc>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = """
A library with limited dependencies containing an HTTP client and server.
"""

[features]
default = ["std", "openssl"]
std = []

[dependencies]
hashbrown = "^0.3"
openssl = { version = "^0.10", optional = true }
