#!/bin/bash

set -ex

cargo build
cargo build --no-default-features
cargo build --no-default-features --features std,ssl-openssl
cargo build --no-default-features --features std,ssl-rustls
cargo check

cargo test
cargo test --no-default-features --features std,ssl-openssl
cargo test --no-default-features --features std,ssl-rustls

cargo run --example readme
cargo run --example connection_reuse

echo "All tests passed"
