#!/bin/bash

set -ex

cargo build
cargo build --no-default-features
cargo build --no-default-features --features std,ssl-rustls
cargo check

cargo test

# sadly not fully working yet
# cargo test --no-default-features --features std,ssl-rustls
