name: CI

on: [push, pull_request]
defaults:
  run:
    shell: bash

jobs:
  prepush:
    runs-on: ubuntu-latest
    container: rust:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install target
        run: rustup target add thumbv7m-none-eabi
      - name: Run
        run: ./prepush
